language: node_js
node_js: "7"
cache: yarn
before_script: yarn
script: yarn run build
deploy:
  provider: pages
  github_token: $GITHUB_TOKEN
  local_dir: dist
  skip_cleanup: true
  on:
    branch: master
